#
# for GMT3.4.5, use the next two lines
#GGRD_INC_FLAGS = -I$(GMTHOME)/include -I$(NETCDFHOME)/include  -DUSE_GMT3
#GGRD_LIBS_LINKLINE = -lggrd -lgmt -lnetcdf 
# 
#
# for GMT version >= 4.1.2, uncomment the next two lines
#
# quad precision
ADD_FLAGS = -DHC_PRECISION=32 -O2 
#ADD_FLAGS = -O2 

GGRD_INC_FLAGS = -I$(GMTHOME)/include -I$(NETCDFHOME)/include 
GGRD_LIBS_LINKLINE = -lggrd -lgmt -lpsl -lnetcdf 
