#!/bin/bash
#
# create a tar file 
#
ver=${1-1.0}
date=`date '+%m%d%y'`

tf=$HOME/tmp/hc-$ver.$date.tgz 

rm -rf $HOME/tmp/hc
mkdir $HOME/tmp/hc
mkdir $HOME/tmp/hc/example_data
mkdir $HOME/tmp/hc/prem/
mkdir $HOME/tmp/hc/hcplates/

cp  *.c *.h Makefile Makefile.include  README.TXT calc_vel_and_plot \
     $HOME/tmp/hc
cp example_data/* $HOME/tmp/hc/example_data/
cp prem/prem* $HOME/tmp/hc/prem/
cp hcplates/* $HOME/tmp/hc/hcplates/


cd $HOME/tmp/

tar --create --gzip --verbose --file $tf hc/

rm -r hc/

cd -

mv $tf $HOME/public_html/software/
tf=$HOME/public_html/software/hc-$ver.$date.tgz 

echo $0: output in $tf

if [ -s $tf ];then
    cd $HOME/public_html/
    ln -fs software/hc-$ver.$date.tgz hc-recent.tgz
    echo $0: linked to  hc-recent.tgz in `pwd`
    cd -
fi

