#!/bin/bash
ver=0.1
date=`date '+%m-%d-%y'`

rm -rf $HOME/tmp/hc
mkdir $HOME/tmp/hc
mkdir $HOME/tmp/hc/example_data
mkdir $HOME/tmp/hc/prem/

cp  *.c *.h Makefile  README.TXT INSTALLATION.TXT calc_vel_and_plot \
     $HOME/tmp/hc
cp example_data/* $HOME/tmp/hc/example_data/
cp prem/prem* $HOME/tmp/hc/prem


cd $HOME/tmp/

tar --create --gzip --verbose --file $HOME/tmp/hc-$ver.$date.tgz hc/

rm -r hc/

cd -
