#!/bin/bash
#
# create a directory with the binaries.  It invokes make, so it needs
# NETCDFHOME and GMTHOME set.  ARCH should not be set.
#
# On Linux and cygwin, invoke as
#
#   LDFLAGS=-static ./make_binary_package
#
# On the Mac, you need to delete the dynamic libraries in
# ~/netcdf/lib/.  This forces the linker to use the static libraries.
# Then you can build static libraries with "./make_binary_package"

ver=1.0

dest=../hc-$ver

rm -rf bin objects
CFLAGS="-O2" make all

mkdir "$dest"
cp README.TXT calc_vel_and_plot "$dest"
mkdir "$dest/example_data" "$dest/prem" "$dest/bin"
cp bin/$ARCH/* "$dest/bin"
strip "$dest/bin/"*
cp example_data/* "$dest/example_data"
cp prem/* "$dest/prem"
mkdir "$dest/hcplates"
cp hcplates/data hcplates/enes hcplates/parameter_file.default hcplates/plates_ids.ixz hcplates/point.j hcplates/README hcplates/run_example.mk "$dest/hcplates"

